### ISSUE TITLE
Cake fail to build .cake script after update Cake.Incubator to 1.1.0

### ISSUE THREAD

**Issue by andreymir** [cake-contrib/Cake.Incubator#22]
Yesterday all worked fine, but today our build started to fail with the following error:
```
[08:24:48]	[Step 3/4] Preparing to run build script...
[08:24:52]	[Step 3/4] Running build script...
[08:24:52]	[Step 3/4] Analyzing build script...
[08:24:52]	[Step 3/4] Processing build script...
[08:24:52]	[Step 3/4] Installing addins...
[08:24:59]	[Step 3/4] Downloading and installing Roslyn...
[08:24:59]	[Step 3/4] Installing packages (using https://packages.nuget.org/api/v2)...
[08:25:01]	[Step 3/4] Copying files...
[08:25:01]	[Step 3/4] Copying Roslyn.Compilers.CSharp.dll...
[08:25:01]	[Step 3/4] Copying Roslyn.Compilers.dll...
[08:25:01]	[Step 3/4] Deleting installation directory...
[08:25:02]	[Step 3/4] Compiling build script...
[08:25:03]	[Step 3/4] Error: error CS0009: Metadata file 'F:\TeamCity\buildAgent2\work\6cd4f52e96e9c2ea\src\BuildScripts\tools\Addins\Cake.Incubator\lib\net45\Cake.Incubator.dll' could not be opened -- 'MetadataReaderException: UnknownTables'
[08:25:03]	[Step 3/4] Process exited with code 1
[08:25:03]	[Step 3/4] Step Build site (PowerShell) failed
```

When I specified the version in the import `#addin nuget:?package=Cake.Incubator&version=1.0.56` the build work again.

**Comment by wwwlicious** [comment]
Thanks @andreymir, I am aware of this and am working on putting out a release shortly.
